!pip install accelerate==0.21.0
!pip install peft==0.4.0
!pip install bitsandbytes==0.40.2
!pip install transformers==4.31.0
!pip install trl==0.4.7
!pip install torch
!pip install tensorboard
!pip install pyttsx3
!pip install whisper
!pip install accelerate
!pip install streamlit -q
!pip install git+https://github.com/openai/whisper.git
!pip install pyttsx3
!pip install whoosh
!pip install whoosh-index
!pip install gtts
!pip install pydub
!pip install pinecone
!pip install sentence_transformers
!pip install nltk
!pip install client
!pip istall pinecone-client
!pip install dotenv
!pip install langchain_community
!pip install langchain_text_splitters
!pip install langchain_openai
!pip install langchain_pinecone
!pip install openai
